FROM apache/airflow:2.5.1

USER root


RUN apt-get update \
    && apt-get install -y wget \
    && apt-get install -y unzip \
    && apt-get install -y git \
    && rm -rf /var/lib/apt/lists/*



USER airflow

WORKDIR /app

ADD . /app

#COPY requirements.txt /requirements.txt

RUN pip3 install --user --upgrade pip

RUN pip3 install --no-cache-dir --user -r requirements.txt

